<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1639014358300' stop='1639014358327'>
    <name>Login feature test</name>
    <title>Login feature test</title>
    <test-cases>
        <test-case start='1639014358300' status='failed' stop='1639014363055'>
            <name>As a user I would like to log in to Todoist with a valid credentials</name>
            <title>As a user I would like to log in to Todoist with a valid credentials</title>
            <labels>
                <label name='severity' value='undefined'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='User Agent' value='Microsoft Edge 96.0.1054.43 / Windows 10'/>
            </parameters>
            <steps/>
            <attachments/>
            <failure>
                <message>AssertionError: expected false to be truthy</message>
                <stack-trace>AssertionError: expected false to be truthy
                
                Browser: Chrome 96.0.4664.45 / Windows 10
                
                    7 |fixture('Login feature test')
                    8 |    .page `${URL.BASE_URL}`
                    9 |    test('As a user I would like to log in to Todoist with a valid credentials', async t=> {
                   10 |        await t
                   11 |            .useRole(VALID_USER)
                 > 12 |            .expect(taskPage.todayTitle.exists).ok() //{timeout:6000} sometimes is not passing the test.
                   13 |    })
                   14 |    
                   15 |    test.meta('type', 'smoke')('As a user I logged in with an invalid credentials', async t=> {
                   16 |        await loginPage
                   17 |            .submitLoginForm(CREDENTIALS.INVALID_USER.EMAIL, CREDENTIALS.INVALID_USER.PASSWORD)
                
                   at &lt;anonymous> (C:\Users\Ilse\Documents\GitHub\QABootcamp\pom\tests\login.test.js:12:49)
                   at asyncGeneratorStep (C:\Users\Ilse\Documents\GitHub\QABootcamp\pom\tests\login.test.js:4:263)
                   at _next (C:\Users\Ilse\Documents\GitHub\QABootcamp\pom\tests\login.test.js:4:601)
                   at &lt;anonymous> (C:\Users\Ilse\Documents\GitHub\QABootcamp\pom\tests\login.test.js:4:766)
                   at &lt;anonymous> (C:\Users\Ilse\Documents\GitHub\QABootcamp\pom\tests\login.test.js:4:507)
                   at &lt;anonymous> (C:\Users\Ilse\Documents\GitHub\QABootcamp\pom\tests\login.test.js:9:9)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>